services:
  ########################################## FRONTEND VUE ##########################################
  frontend:
    container_name: whispr-frontend-dev
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_NEST_API_URL=http://localhost:3000
    command: ["npm", "run", "dev", "--", "--host"]

  ########################################## BACKEND NEST ###########################################
  nest:
    container_name: whispr-backend-dev
    build:
      context: ./backend
      dockerfile: Dockerfile.nest 
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      # Variables pour Postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=chatdb

    depends_on:
      - postgres

    command: ["npm", "run", "start:dev"]

  ########################################## POSTGRES ###############################################
  postgres:
    image: postgres:15-alpine
    container_name: whispr-db-dev
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: chatdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
